name: Latest

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  verify:
    name: Verify

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [^12, ^14]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install
        run: npm i
      - name: Test
        run: npm t
      - name: Lint
        run: npm run lint
      - name: Types
        run: npm run types

